# -*- coding: utf-8 -*-
"""pages/1_Subir_PDF

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nYnSgD0OFShUtW9HIwAESSQW6K8aBE2X
"""

import streamlit as st
import os

# Carpeta donde se guardarán los PDFs
CARPETA_PDFS = "pdfs_subidos"
os.makedirs(CARPETA_PDFS, exist_ok=True)

st.title("📤 Subir nuevo archivo PDF")

st.markdown("""
Aquí puedes subir archivos PDF para analizarlos más tarde con el sistema.
""")

# Subida del archivo
archivo_pdf = st.file_uploader("Selecciona un archivo PDF", type=["pdf"])

if archivo_pdf:
    ruta_archivo = os.path.join(CARPETA_PDFS, archivo_pdf.name)

    # Guardar el archivo en la carpeta
    with open(ruta_archivo, "wb") as f:
        f.write(archivo_pdf.read())

    st.success(f"✅ Archivo '{archivo_pdf.name}' guardado correctamente.")
    st.info("Ahora puedes ir a la pestaña de preguntas y usar este PDF (cuando lo integremos al índice).")