# -*- coding: utf-8 -*-
"""pages/2_Ver_Archivos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZWJKSyL0cprvruVB9P5nI6LvfO7SSy2T
"""

import streamlit as st
import os

# Carpeta donde se guardan los PDFs subidos
CARPETA_PDFS = "pdfs_subidos"

st.title("📚 Ver archivos cargados")

if not os.path.exists(CARPETA_PDFS):
    st.warning("Aún no se han subido archivos.")
else:
    archivos = os.listdir(CARPETA_PDFS)

    if archivos:
        st.markdown("### Archivos PDF disponibles:")
        for archivo in archivos:
            st.write(f"📄 {archivo}")
    else:
        st.info("No hay archivos subidos todavía. Ve a la pestaña 'Subir PDF' para agregar uno.")